name: build
description: 'Build Pointivo container images'
#inputs:
outputs:
  imageTag:
    description: Docker Image Tag
    value: ${{ steps.build.outputs.imageTag }}
  semver:
    description: SEMVER
    value: ${{ steps.build.outputs.semver }}
  commitHash:
    description: Commit SHA Short
    value: ${{ steps.build.outputs.commitHash }}
runs:
  using: composite
  steps:
    - id: build
      run: ${GITHUB_ACTION_PATH}/build.sh
      shell: bash